name: OneHundredGenerator
description: Minecraft 1.0.0 world generator.
author: DjDCH
main: com.djdch.bukkit.onehundredgenerator.OneHundredGenerator
version: 0.1
load: startup
website: http://dev.bukkit.org/server-mods/onehundredgenerator/
